use_frameworks!

target 'FWRouter_Example' do
  pod 'FWRouter', :path => '../'

  target 'FWRouter_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
